SIM = questa

TOPLEVEL_LANG = verilog
TOPLEVEL = fir

VERILOG_SOURCES += $(PWD)/../rtl/fir.sv
VERILOG_SOURCES += $(PWD)/../rtl/fir_mac.sv
VERILOG_SOURCES += $(PWD)/../rtl/fir_stage.sv

MODULE = test_fir

include $(shell cocotb-config --makefiles)/Makefile.sim
