-------------------------------------------------------------------------------
-- COPYRIGHT (c) ERICSSON AB, 2018
-- The copyright to the document(s) herein is the property of
-- Ericsson AB, Sweden.
--
-- The document(s) may be used and/or copied only with the written
-- permission from Ericsson AB, or in accordance with the terms and
-- conditions stipulated in the agreement/contract under which
-- the document(s) have been supplied.
--
-- All rights reserved.
-------------------------------------------------------------------------------
--
-- Author:     , 
-- Created:    Autogenerated by perl script from Excel sheet, 2018-09-20
--
-------------------------------------------------------------------------------
-- Description: OPB slave for DPD0
--   DO NOT MAKE CHANGES IN THIS FILE!!
--   This is automatically generated
--   
--   Read and Write registers takes 3 cycles, 
--   Write MEM takes 5 cycles, Read MEM takes 5 cycles
-------------------------------------------------------------------------------
-- VHDL Version: VHDL '93
--
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
-- Libraries
-------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- ****************************************************************************
-- ****************************************************************************
-- ****                                                                    ****
-- ****   DO NOT MAKE CHANGES IN THIS FILE!!                               ****
-- ****                                                                    ****
-- ****************************************************************************
-- ****************************************************************************

-------------------------------------------------------------------------------
-- Entity declaration for OPB-IF for DPD0
-------------------------------------------------------------------------------
entity dpd0_opb_if is
  generic (
    baseaddr_g   : natural := 16#0002200#  -- baseaddr = 0x00022000
  );
  port (
    -- clock and reset
    clk_opb      : in     std_logic;
    rst_opb    : in     std_logic;

    -- OPB bus signals
    opb_select   : in     std_logic;
    opb_fwxfer   : in     std_logic;
    opb_hwxfer   : in     std_logic;
    opb_rnw      : in     std_logic;
    opb_seqaddr  : in     std_logic;
    opb_dbus     : in     std_logic_vector(0 to 31);
    opb_abus     : in     std_logic_vector(0 to 31);
    sl_errack    : out    std_logic;
    sl_retry     : out    std_logic;
    sl_toutsup   : out    std_logic;
    sl_xferack   : out    std_logic;
    sl_fwack     : out    std_logic;
    sl_hwack     : out    std_logic;
    sl_dbusen    : out    std_logic;
    sl_dbus      : out    std_logic_vector(0 to 31);

    -- signals to memory DPD0_RAM_MEM
    dpd0_ram_mem_busy      : in     std_logic;
    dpd0_ram_mem_sel       : out    std_logic;
    dpd0_ram_mem_rd        : out    std_logic;
    dpd0_ram_mem_wr        : out    std_logic;
    dpd0_ram_mem_rd_data   : in     std_logic_vector(31 downto 0);
    dpd0_ram_mem_wr_data   : out    std_logic_vector(31 downto 0);
    dpd0_ram_mem_addr      : out    std_logic_vector(10 downto 0)
  );
end entity dpd0_opb_if;
