SIM ?= questa

TOPLEVEL_LANG = verilog
TOPLEVEL = axi4s_reg

PWD=$(shell pwd)

VERILOG_SOURCES = $(PWD)/../rtl/axi4s_reg.sv

MODULE := test_axi4s_reg

include $(shell cocotb-config --makefiles)/Makefile.sim
